# Generated by Django 5.0.4 on 2024-04-17 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria_elemento', '0001_initial'),
        ('tipo_elemento', '0002_alter_tipoelemento_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaDevencimiento', models.DateTimeField(auto_created=True)),
                ('CodigoSena_Material', models.CharField(max_length=255)),
                ('Nombre_Material', models.CharField(max_length=255)),
                ('Descripcion_Material', models.CharField(max_length=255)),
                ('stock', models.IntegerField(default=0)),
                ('unidad_medida', models.IntegerField(max_length=255)),
                ('producto_perecedero', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('Categoria_Material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categoria_elemento.categoriaelementos')),
                ('Tipo_Material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipo_elemento.tipoelemento')),
            ],
        ),
    ]
