# Generated by Django 5.0.4 on 2024-04-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elemento_material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementomaterial',
            name='unidad_medida',
            field=models.CharField(max_length=255),
        ),
    ]
