# Generated by Django 5.0.4 on 2024-04-18 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elemento_material', '0002_alter_elementomaterial_unidad_medida'),
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementomaterial',
            name='sitio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sitio.sitio'),
        ),
    ]
