# Generated by Django 5.0.4 on 2024-04-18 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='programa_area',
        ),
    ]
