# Generated by Django 5.0.4 on 2024-04-17 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_sitio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sitio', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('FichaTecnica', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('persona_encargada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tipo_sitio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipo_sitio.tipo_sitio')),
            ],
        ),
    ]
