# Generated by Django 5.0.4 on 2024-04-18 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0002_remove_area_programa_area'),
        ('programa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='area_programa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='area.area'),
        ),
    ]
